### ISSUE TITLE
IllegalStateException when open sample-composite-project

### ISSUE THREAD

**Issue by d-amelin** [jmix-projects/sample-composite-project#1]
1. Install Jmix plugin 1.1.3-211 on IDEA IntelliJ IDEA 2021.1.3 (Ultimate Edition) Build #IU-211.7628.21, built on June 30, 2021
Download https://github.com/jmix-projects/sample-composite-project
Open project as 'sample-composite-project' directory. Should open as 'sample-composite-project\all' directory in normal case. This issue about wrong case.

expected: no exceptions 
got:
`java.lang.IllegalStateException
	at com.haulmont.jmixstudio.buildsystem.gradle.GradleBuildFilesProvider.getBuildGradle(GradleBuildFilesProvider.kt:74)
	at com.haulmont.jmixstudio.buildsystem.gradle.GradleBuildFilesProvider.searchBuildFiles(GradleBuildFilesProvider.kt:45)
	at com.haulmont.jmixstudio.buildsystem.gradle.ui.projecttree.JmixBuildScriptSection.getChildrenImpl(JmixBuildScriptSection.kt:31)
	at com.haulmont.jmixstudio.intellij.ui.cubatree.AbstractJmixSection.getChildren(AbstractJmixSection.kt:56)
	at com.haulmont.jmixstudio.intellij.ui.cubatree.jmix.JmixProjectModuleNode.getChildrenImpl(JmixProjectModuleNode.kt:53)
	at com.haulmont.jmixstudio.intellij.ui.cubatree.AbstractJmixSection.getChildren(AbstractJmixSection.kt:56)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:34)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:382)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:298)
	at com.intellij.ui.tree.StructureTreeModel$Node.isLeaf(StructureTreeModel.java:558)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:334)
	at com.intellij.ui.tree.LeafState.get(LeafState.java:64)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:574)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:547)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:316)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
`

2. "Gradle build scripts found" message will appears. Click 'import'
there are multiple "build.gradle not found in project" errors in IDEA "Error log" tab.

3. "New Jmix version is available" message will appears. Click "Open project properties...". Change Jmix version to 1.1.1. Click "OK".
"build.gradle not found in project" will appears again. Cant close "Jmix Project Properties" dialog.

[idea.log](https://github.com/jmix-projects/sample-composite-project/files/7717012/idea.log)

**Comment by d-amelin** [comment]
Maybe this is wrong repo for that issue. Where is public repo for Jmix plugin issues? I have not found it at https://github.com/Haulmont and https://github.com/orgs/jmix-projects/repositories?type=all
